changed user table to student and added login and register tests
guaj/SemesterPlanner-Server pull request #34
Opened 2022-10-26 00:41 UTC by EyalAzimov

2022-10-27 00:18 UTC, based-kwl commented
Just a note: these http tests to mongo won't run properly until we have a public API available.

2022-10-27 22:01 UTC, guaj commented
> Just a note: these http tests to mongo won't run properly until we have a public API available. So the CircleCI tests failing is expected.
> 
> I have ran the tests locally and they work when the server is running.

Hey, sorry just wen through this comment. The ec2 isntance went down. Looking to boot it up. Althought, jest test should work out of the box, meaning that they should be able to run without any data base connections. Make sure you are testing the right thing.

2022-10-27 23:15 UTC, based-kwl commented
> > Just a note: these http tests to mongo won't run properly until we have a public API available. So the CircleCI tests failing is expected.
> > I have ran the tests locally and they work when the server is running.
> 
> Hey, sorry just wen through this comment. The ec2 isntance went down. Looking to boot it up. Althought, jest test should work out of the box, meaning that they should be able to run without any data base connections. Make sure you are testing the right thing.

This is not what i meant. The tests in question do work if you have the secret key, but since connecting to the database requires a secret key which is not included in the repo, CircleCI will always fail. It doesn't mean that the tests are wrong, it's simply because we are using MongoDB atlas, a cloud db and not a local db. 

Once we have a permanent backend server up and running on a 24/7 server with an accessible api (e.g. https://www.semester-planner.com/api/student/ instead of localhost:5000), these test will function as intended after changing the http request address to that of the API.

2022-10-28 16:12 UTC, guaj commented
> > > Just a note: these http tests to mongo won't run properly until we have a public API available. So the CircleCI tests failing is expected.
> > > I have ran the tests locally and they work when the server is running.
> > 
> > 
> > Hey, sorry just wen through this comment. The ec2 isntance went down. Looking to boot it up. Althought, jest test should work out of the box, meaning that they should be able to run without any data base connections. Make sure you are testing the right thing.
> 
> This is not what i meant. The tests in question do work if you have the secret key, i.e. if you run the test locally, but since the key is not included in the repo (for obvious security reasons), CircleCI will always fail because it cannot make those http requests and the tests will fail. It doesn't mean that the tests are wrong, it's simply because we are using MongoDB atlas, a cloud db and not a local db.
> 
> Once we have a permanent backend server up and running on a 24/7 server with an accessible api (e.g. https://www.semester-planner.com/api/student/ instead of localhost:5000), these test will function as intended after changing the http request address to that of the API.

these tests don't work because env variables are not passed into circle ci. Im fixing it and ill write a test for the mongodb connection

2022-10-28 16:30 UTC, guaj requested changes

2022-10-28 16:30 UTC, guaj commented on __test__/Student_test_data.js
> +
this should be passed as an env varible. Ill add them to the circle ci env

2022-10-28 16:30 UTC, guaj commented on src/routes/Student.js
> -    User.findByIdAndDelete(req.params.id)
we don't need both, just the email route is fine

2022-10-28 16:30 UTC, guaj commented on src/routes/Student.js
> +    const newStudent = new Student({
student creation responsability should not be in the route. We can define a student factory in another file that will create students based on the data passed in the request. We want low coupling here.

2022-10-28 16:30 UTC, guaj commented on src/routes/login.js
> +const Student = require("../models/Student.model");
constant usually starts with lower letters not upper ones. No consistency in the files.

2022-10-28 16:30 UTC, guaj commented on __test__/Student.spec.js
> +  let httpResponse = await axios.post('http://localhost:5000/Student/add',registerPayload)
Do not use axios here ... import the route directly and use it.
see here  : https://fek.io/blog/how-to-add-unit-testing-to-express-using-jest

2022-10-28 16:30 UTC, guaj commented on __test__/Student.spec.js
> +  let httpResponse = await axios.post('http://localhost:5000/login', loginPayload)
same

2022-10-28 16:30 UTC, guaj commented on __test__/Student.spec.js
> +  let httpResponse = await axios.delete('http://localhost:5000/student/email/ram@b.ca')
same

2022-10-28 17:06 UTC, based-kwl commented
I am legitimately not sure what you are trying to do. I'm telling you CircleCI doesn't have our secret key to connect to mongo... yet you keep trying to make it connect via other means. 

If you want to have the same environment that CircleCI has, delete your .env file and try to pass the test...

2022-10-28 17:07 UTC, guaj commented
> I am legitimately not sure what you are trying to do. I'm telling you CircleCI doesn't have our secret key to connect to mongo... yet you keep trying to make it connect via other means.
> 
> If you want to have the same environment that CircleCI has, delete your .env file and try to pass the test...

circle ci has the secrents ... we can discuss this in the meeting tonight.

2022-10-28 18:06 UTC, based-kwl commented
> > I am legitimately not sure what you are trying to do. I'm telling you CircleCI doesn't have our secret key to connect to mongo... yet you keep trying to make it connect via other means.
> > If you want to have the same environment that CircleCI has, delete your .env file and try to pass the test...
> 
> circle ci has the secrets ... my test (mongoDbConnection.spec.ts) pass in the pipeline. We can discuss this in the meeting tonight.

Yeah you were right, changed the tests to not use axios and fixed some consistency issues.

2022-10-30 12:46 UTC, RamB98 commented
pull request reviewed  all test have passed, merging the branch

2022-10-30 12:46 UTC, merged