Repository pattern implementation
guaj/SemesterPlanner-Server pull request #71
Opened 2022-11-18 22:18 UTC by based-kwl

- Repository pattern implemented for all existing routes
- Model schema changes
- Code cleanup

model schemas changes:
- removed `messages` attribute from `StudyRoom` - retrieve the messages using the available routes.
- `StudyRooms` -> `studyRooms` in `Student` schema.
- `sID` -> `studyRoomID` in `StudyRoom` schema and everywhere else that uses it
- `mID` -> `messageID` in `Message` schema
- `cnID` -> `courseNotesID` in `CourseNotes` schema
- `cID` -> `calendarID` in `Calendar` schema
- added `eventID` to `Event` schema

TODO:
validation

2022-11-19 20:06 UTC, guaj commented
need to create a branch in front end to apply the changes in the var namings. We cant approve this request as long as its not breaking the functionnality of our deployed app .

2022-11-19 21:30 UTC, mnashat commented
> need to create a branch in front end to apply the changes in the var namings. We cant approve this request as long as its breaking the functionnality of our deployed app . Else good work on the code. Code is clean and well documented.

Agreed. Very well documented and structured. Great job! And as mentioned, we can't merge this yet as this will break compatibility with frontend live deployment. We'll refactor frontend and merge both. Well done!

2022-11-19 21:33 UTC, mnashat commented
It is extremely important that new backend branches be created from this branch so that new frontend and backend implementations are consistent from this point onwards (until the current frontend is updated for compatibility). We don't want newer branches implementing outdated routes/code structure/branches, as this will be a huge pain to fix later on. Please take note everyone!

@based-kwl @guaj @RamB98 @EyalAzimov @jacobmathewlopez

2022-11-19 21:36 UTC, guaj commented
> It is extremely important that new backend branches be created from this branch so that new frontend and backend implementations are consistent from this point onwards (until the current frontend is updated for compatibility). We don't want newer branches implementing outdated routes/code structure/branches, as this will be a huge pain to fix later on. Please take note everyone!
> 
> @based-kwl @guaj @RamB98 @EyalAzimov @jacobmathewlopez

This branch needs to be merged before we start from this branch. Else we will push things that are not actually working. I recommend we do this beginning of next sprint.

2022-11-20 18:28 UTC, mnashat commented
> > It is extremely important that new backend branches be created from this branch so that new frontend and backend implementations are consistent from this point onwards (until the current frontend is updated for compatibility). We don't want newer branches implementing outdated routes/code structure/branches, as this will be a huge pain to fix later on. Please take note everyone!
> > @based-kwl @guaj @RamB98 @EyalAzimov @jacobmathewlopez
> 
> This branch needs to be merged before we start from this branch. Else we will push things that are not actually working. I recommend we do this beginning of next sprint.

Noted!

2022-11-20 18:32 UTC, mnashat commented
> > It is extremely important that new backend branches be created from this branch so that new frontend and backend implementations are consistent from this point onwards (until the current frontend is updated for compatibility). We don't want newer branches implementing outdated routes/code structure/branches, as this will be a huge pain to fix later on. Please take note everyone!
> > @based-kwl @guaj @RamB98 @EyalAzimov @jacobmathewlopez
> 
> This branch needs to be merged before we start from this branch. Else we will push things that are not actually working. I recommend we do this beginning of next sprint.

Agreed, but it looks like some things are already broken due to schema changes on the database, so we might need to update everything ASAP anyways.

2022-11-20 20:51 UTC, mnashat requested changes
There are a lot of issues in this refactor such as invalid calls and returns. Some of the routes are also not implemented correctly. Please check my comments or some examples of these. Please review all changes and correct the code appropriately. Thanks!

2022-11-20 20:51 UTC, mnashat commented on src/routes/room.js
> +  StudyRoomRepository.findOne(req.body.studyRoomID)
Add `const data = req.body;` here. Variable `data` is not defined, so if conditions aren't executing properly.

2022-11-20 20:51 UTC, mnashat commented on src/routes/room.js
> +      StudyRoomRepository.updateOne(room)
Method `updateOne(...)` does not exist in `StudyRoomRepository`. For updating a room, the method is called 'save(...)`. Either change this line to `StudyRoomRepository.save(...)` or rename the method in `StudyRoomRepository` to `updateOne(...)`.

2022-11-20 20:51 UTC, mnashat commented on src/repository/studyRoomRepository.js
> +            newRoom.save((err, room) => {
Method `save(...)` does not exist in `createStudyRoom`.

2022-11-20 20:51 UTC, mnashat commented on src/repository/studyRoomRepository.js
> +        return new Promise((resolve, reject) => {
Some promise returns such as this one seems to be invalid. Please recheck your code to make sure all promises are returned properly. It is also causing a lot of calls (such as those in `room.js`) to not correctly recognize `.then(...)` calls, which leads to backend `console.log(...)` calls to not print anything in the backend console.

2022-11-20 23:59 UTC, mnashat approved these changes
Great job on the refactoring! Approved.

2022-11-21 00:14 UTC, guaj approved these changes

2022-11-21 00:16 UTC, merged