Sp 27/study stats
guaj/SemesterPlanner-Server pull request #91
Opened 2022-12-11 21:14 UTC by jacobmathewlopez

- Added endpoint to find events of type 'course' by requesting user within a week (in the future)
- Adjusted validator to accept boolean values

2023-01-22 23:53 UTC, guaj requested changes

2023-01-22 23:53 UTC, guaj commented on src/routes/login.js
> +  console.log()
remove logs before merging please.

2023-01-23 01:18 UTC, mnashat commented
As mentioned in the frontend PR [here](https://github.com/based-kwl/SemesterPlanner-client/pull/108#issuecomment-1399664928), please do not make `actualStartTime` and `actualEndTime` required, as not all events are expected to have them. Moreso, newly created events are expected to not have actual start and end times when created.

2023-02-13 19:23 UTC, guaj approved these changes

2023-03-08 20:22 UTC, based-kwl approved these changes

2023-03-12 22:54 UTC, merged